version = 0.1

[default.deploy.parameters]
stack_name = "wildfire-live-map"
region = "us-east-1"
profile = "wildfire"
resolve_s3 = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
